server:
  port: 8083

spring:
  application:
    name: quntui-bao
  profiles:
    active: prod  # 默认开发环境
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.quntui.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.quntui: debug