# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://rm-bp1m2om694f9mmx6dto.mysql.rds.aliyuncs.com:3306/quntui_bao?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: fish
    password: qtz#923812

# Telegram 开发环境配置
telegram:
  bot-token: 8380175815:AAG-ynueRiEkNWDFULpc8VNhRD5b3B3f0Cc
  api-id: 21791619
  api-hash: 282e7c380c97f10391003d88c48701fe
  proxy:
    enabled: true
    host: 127.0.0.1
    port: 7890