# 开发环境配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://rm-bp1m2om694f9mmx6dto.mysql.rds.aliyuncs.com:3306/quntui_bao?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: fish
    password: qtz#923812
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionInitSql: SET NAMES utf8mb4
      connection-sql: SET CHARACTER SET utf8mb4

# Python 机器人配置
python:
  bot:
    script: bot.py
    workdir: /tmp/python

# Telegram 开发环境配置
telegram:
  bot:
    token: 8380175815:AAG-ynueRiEkNWDFULpc8VNhRD5b3B3f0Cc
  api:
    id: 21791619
    hash: 282e7c380c97f10391003d88c48701fe
  proxy:
    enabled: true
    host: 127.0.0.1
    port: 7890