server:
  port: 8083

spring:
  application:
    name: quntui-bao
  profiles:
    active: prod  # 默认开发环境
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.quntui.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Python 机器人配置
python:
  bot:
    script: python/bot.py
    workdir: /tmp/python

# Telegram 配置
telegram:
  bot:
    token: ${BOT_TOKEN:}
  api:
    id: ${API_ID:21791619}
    hash: ${API_HASH:282e7c380c97f10391003d88c48701fe}

logging:
  level:
    com.quntui: debug